version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "8081:8081"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:8080"
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always
