version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    restart: always
    container_name: backend_app

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    restart: always
    container_name: frontend_app
